# ⚙️ Configuración del Dispositivo
device_id: "514c:8850"
rows: 4
cols: 3
wheels: 2

# 💡 Configuración de Luces (Modo Dual)
led:
  mode: 1
  r: 255
  g: 0
  b: 0

# ⌨️ Mapeo de Teclas y Ruedas
keys:
  # --- Fila 1 (Superior) ---
  7: "xdotool key ctrl+Home"           # Ir al Inicio
  11: "xdotool key ctrl+End"           # Ir al Final
  15: "xdotool key ctrl+a"             # Seleccionar Todo

# --- Fila 2 Media Superior ---
  6: "xdotool key ctrl+c"             # Copiar
  10: "xdotool key ctrl+v"            # Pegar
  14: "xdotool key ctrl+t"            # Nueva Pesteña

# --- Fila 3 Media Inferior ---
  5: "xdotool key ctrl+z"             # Deshacer
  9: "xdotool key ctrl+y"             # Rehacer
  13: "xdotool key ctrl+w"            # Cerrar Pestaña

  # --- Fila 4 Inferior ---
  4: "xdotool key ctrl+shift+c"       # Copiar
  8: "xdotool key ctrl+shift+v"       # Pegar
  12: "xdotool key ctrl+q"            # Sakir

  # ---  Rueda 1 (Knob Izquierdo) ---
  19: "pactl set-sink-volume @DEFAULT_SINK@ -1%"  # Giro Izquierda: Bajar Vol
  20: "pactl set-sink-mute @DEFAULT_SINK@ toggle" # Presionar: Mute
  21: "pactl set-sink-volume @DEFAULT_SINK@ +1%"  # Giro Derecha: Subir Vol

  # --- Rueda 2 (Knob Derecho) ---
  22: "xdotool key ctrl+minus"    # Giro Izquierda: Zoom Minus
  23: "xdotool key ctrl+0"        # Presionar: Reestablece Zoom
  24: "xdotool key ctrl+plus"     # Giro Derecha: Zoom Plus

# Modifiers:
#  - ctrl
#  - shift
#  - alt / opt
#  - win / cmd
#  - rctrl
#  - rshift
#  - ralt / ropt
#  - rwin / rcmd

# Keys:
#  - a
#  - b
#  - ca
#  - d
#  - e
#  - f
#  - g
#  - h
#  - i
#  - j
#  - k
#  - l
#  - m
#  - n
#  - o
#  - p
#  - q
#  - r
#  - s
#  - t
#  - u
#  - v
#  - w
#  - x
#  - y
#  - z
#  - 1
#  - 2
#  - 3
#  - 4
#  - 5
#  - 6
#  - 7
#  - 8
#  - 9
#  - 0
#  - enter
#  - escape
#  - backspace
#  - tab
#  - space
#  - minus
#  - equal
#  - leftbracket
#  - rightbracket
#  - backslash
#  - nonushash
#  - semicolon
#  - quote
#  - grave
#  - comma
#  - dot
#  - slash
#  - capslock
#  - f1
#  - f2
#  - f3
#  - f4
#  - f5
#  - f6
#  - f7
#  - f8
#  - f9
#  - f10
#  - f11
#  - f12
#  - printscreen
#  - macbrightnessdown
#  - macbrightnessup
#  - insert
#  - home
#  - pageup
#  - delete
#  - end
#  - pagedown
#  - right
#  - left
#  - down
#  - up
#  - numlock
#  - numpadslash
#  - numpadasterisk
#  - numpadminus
#  - numpadplus
#  - numpadenter
#  - numpad1
#  - numpad2
#  - numpad3
#  - numpad4
#  - numpad5
#  - numpad6
#  - numpad7
#  - numpad8
#  - numpad9
#  - numpad0
#  - numpaddot
#  - nonusbackslash
#  - application
#  - power
#  - numpadequal
#  - f13
#  - f14
#  - f15
#  - f16
#  - f17
#  - f18
#  - f19
#  - f20
#  - f21
#  - f22
#  - f23
#  - f24

# Custom key syntax (use decimal code): <110>

# Media keys:
#  - next
#  - previous / prev
#  - stop
#  - play
#  - mute
#  - volumeup
#  - volumedown
#  - favorites
#  - calculator
#  - screenlock
